@startuml

title __COMMON's Class Diagram__\n

  namespace com.training.petstore {
    namespace util.common {
      class com.training.petstore.util.common.CommonUtil {
          {static} + CHECK_ACCOUNT : int
          {static} + CHECK_ASSET : int
          {static} + CHECK_NICKNAME : int
          {static} + CHECK_PASSWORD : int
          {static} + MainThreadToast()
          {static} + dateToString()
          {static} + isAccountInputOK()
          {static} + isMailBox()
          {static} + pickImage()
      }
    }
  }
  

  namespace com.training.petstore {
    namespace util.common {
      class com.training.petstore.util.common.CommonUtil.MyTextWatcher {
          ~ error : String
          ~ textInputEditText : TextInputEditText
          ~ type : int
          + MyTextWatcher()
          + afterTextChanged()
          + beforeTextChanged()
          + onTextChanged()
      }
    }
  }
  

  namespace com.training.petstore {
    namespace util.common {
      class com.training.petstore.util.common.TestUtil {
          {static} + PET_URLS : String[]
          {static} + PET_VARIETIES : String[]
          {static} + USER_IDS : String[]
          {static} + generateDate()
          {static} + generatePetId()
      }
    }
  }
  

  com.training.petstore.util.common.CommonUtil +-down- com.training.petstore.util.common.CommonUtil.MyTextWatcher
  com.training.petstore.util.common.CommonUtil.MyTextWatcher .up.|> android.text.TextWatcher


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
