@startuml

title __NET's Class Diagram__\n

  namespace com.training.petstore {
    namespace util.net {
      class com.training.petstore.util.net.MyHttpClient {
          {static} + myHttpClient : OkHttpClient
          {static} + getInstance()
      }
    }
  }
  

  namespace com.training.petstore {
    namespace util.net {
      class com.training.petstore.util.net.NetImplementation {
          {static} - TAG : String
          {static} + accountDelete()
          {static} + accountLogin()
          {static} + accountModify()
          {static} + accountRegister()
          {static} + addToCart()
          {static} + allArbitration()
          {static} + allTransactions()
          {static} + cartDelete()
          {static} + dealWithArbitration()
          {static} + getCartPets()
          {static} + isCartExisted()
          {static} + isNotWebConnect()
          {static} + petDelete()
          {static} + petModify()
          {static} + petRegister()
          {static} + queryAccount()
          {static} + requestArbitration()
          {static} + selectByPetId()
          {static} + selectByUserId()
          {static} + sendTransaction()
          {static} + uploadImage()
          {static} - accountNotExisted()
          {static} - arbitrationNotExisted()
          {static} - petNotExisted()
          {static} - transactionNotExisted()
      }
    }
  }
  

  namespace com.training.petstore {
    namespace util.net {
      class com.training.petstore.util.net.NetImplementation.CodeAndMsg {
          ~ code : int
          ~ msg : String
          + CodeAndMsg()
      }
    }
  }
  

  com.training.petstore.util.net.NetImplementation +-down- com.training.petstore.util.net.NetImplementation.CodeAndMsg


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
