@startuml

title __CONSTANTS's Class Diagram__\n

  namespace com.training.petstore {
    namespace util.constants {
      class com.training.petstore.util.constants.IntConstants {
          {static} + ACCEPT_ARBITRATION : int
          {static} + ADD_TO_CART : int
          {static} + CODE_DELETE_FAIL : int
          {static} + CODE_DELETE_SUCCESS : int
          {static} + CODE_ERROR : int
          {static} + CODE_EXISTED : int
          {static} + CODE_LOGIN_FAIL : int
          {static} + CODE_LOGIN_SUCCESS : int
          {static} + CODE_MODIFY_FAIL : int
          {static} + CODE_MODIFY_SUCCESS : int
          {static} + CODE_NOT_EXISTED : int
          {static} + CODE_QUERY_FAIL : int
          {static} + CODE_QUERY_SUCCESS : int
          {static} + CODE_REGISTER_FAIL : int
          {static} + CODE_REGISTER_SUCCESS : int
          {static} + FINISH_ARBITRATION_REQUEST : int
          {static} + FINISH_QUERY_ACCOUNT : int
          {static} + FINISH_TRANSACTION : int
          {static} + GET_MARKET_PET : int
          {static} + GET_MY_PET : int
          {static} + GOT_ARBITRATION : int
          {static} + GOT_MARKET_PETS : int
          {static} + GOT_MY_PETS : int
          {static} + GOT_TRANSACTION : int
          {static} + PET_DELETED : int
          {static} + QUERY_ACCOUNT_FAIL : int
          {static} + REJECT_ARBITRATION : int
          {static} + SEND_TRANSACTION_FAIL : int
          {static} + UPLOAD_IMAGE_FAILED : int
          {static} + UPLOAD_IMAGE_SUCCEEDED : int
      }
    }
  }
  

  namespace com.training.petstore {
    namespace util.constants {
      class com.training.petstore.util.constants.StringConstants {
          {static} + ACTION_CREATE_PET : String
          {static} + ACTION_DELETE_PET : String
          {static} + ACTION_MODIFY_PET : String
          {static} + URL_ACCOUNT_REGIST : String
          {static} + URL_ACCOUNT_REMOVE : String
          {static} + URL_ACCOUNT_SELECT : String
          {static} + URL_ACCOUNT_UNIQUEID : String
          {static} + URL_ACCOUNT_UPDATE : String
          {static} + URL_ARBITRATION_ALLARBITRATIONS : String
          {static} + URL_ARBITRATION_REQUEST : String
          {static} + URL_ARBITRATION_SELECT : String
          {static} + URL_ARBITRATION_VERIFY : String
          {static} + URL_BASE : String
          {static} + URL_CART_INSERT : String
          {static} + URL_CART_REMOVE : String
          {static} + URL_CART_SELECT : String
          {static} + URL_CART_UNIQUE : String
          {static} + URL_MARKET_REGISTPET : String
          {static} + URL_MARKET_REMOVEPET : String
          {static} + URL_MARKET_SELECTBYPETID : String
          {static} + URL_MARKET_SELECTBYUSERID : String
          {static} + URL_MARKET_SELECTONSELL : String
          {static} + URL_MARKET_UNIQUEID : String
          {static} + URL_MARKET_UPDATEPET : String
          {static} + URL_TRANSACTION_ALLTRANSACTIONS : String
          {static} + URL_TRANSACTION_SELECT : String
          {static} + URL_TRANSACTION_TRANSFER : String
          {static} + URL_UPLOAD_IMAGE : String
          {static} + URL_UPLOAD_IMAGE_BASE : String
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
